//! Generated by `maestro-ui-preview --scaffold menu-story --output …`.
use maestro_ui_preview::authoring::{
    StoryInput, StoryKey, StorySequence, export_story, menu_story,
};

fn main() -> Result<(), String> {
    let sequence = StorySequence::new("menu-story", "Menu story", 60, 20).inputs([
        StoryInput::Text { text: "sec".into() },
        StoryInput::Key {
            key: StoryKey::Down,
            ctrl: false,
        },
        StoryInput::Key {
            key: StoryKey::Enter,
            ctrl: false,
        },
    ]);
    let story = menu_story(
        sequence,
        file!(),
        "Choose a section",
        ["Overview", "Security", "Settings"]
            .map(str::to_owned)
            .into(),
        "Filter sections",
        "No sections",
    )?;
    println!("{}", export_story(story)?);
    Ok(())
}
